name: lando-example
recipe: laravel
config:
  php: '8.1'
  composer_version: 'latest'
  via: nginx
  webroot: public
  database: mariadb
  cache: none
  xdebug: false

services:
  phpmyadmin:
    type: phpmyadmin

proxy:
  phpmyadmin:
    - hostname: phpmyadmin.lndo.site
